name: CI
on: 
  push:
    branches: ['main']



jobs:
  publish-library:
    # only run if on main branch
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
        
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      
      - name: set up pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: ^7.1.0
          run_install: true

      # compiles and moves the css into
      # the build/css directory
      - name: build css
        run: pnpm build:css
      
      # compile the library to the dist directory
      - name: build library
        run: pnpm build:rollup
      
      - name: Release
        run: |
          pnpm dlx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    

        

      
    
        
        
